app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin.
  baseUrl: http://localhost:3000

backend:
  # Note that the baseUrl should be the URL that the browser and other clients
  # should use when communicating with the backend, i.e. it needs to be
  # reachable not just from within the backend host, but from all of your
  # callers. When its value is "http://localhost:7007", it's strictly private
  # and can't be reached by others.
  baseUrl: http://localhost:3000
  # The listener can also be expressed as a single <host>:<port> string. In this case we bind to
  # all interfaces, the most permissive setting. The right value depends on your specific deployment.
  listen: ':3000'

  # config options: https://node-postgres.com/apis/client
  # database:
  #   client: pg
  #   connection:
  #     host: ${POSTGRES_HOST}
  #     port: ${POSTGRES_PORT}
  #     user: ${POSTGRES_USER}
  #     password: ${POSTGRES_PASSWORD}
      # https://node-postgres.com/features/ssl
      # you can set the sslmode configuration option via the `PGSSLMODE` environment variable
      # see https://www.postgresql.org/docs/current/libpq-ssl.html Table 33.1. SSL Mode Descriptions (e.g. require)
      # ssl:
      #   ca: # if you have a CA file and want to verify it you can uncomment this section
      #     $file: <file-path>/ca/server.crt

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    # own catalog-info
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/catalog-info.yaml

    # scaffolder / software template
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/catalog-examples/template/template.yaml
      rules:
        - allow: [Template]

    # adr plugin
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/catalog-examples/adr-example.yaml

    # bookmarks plugin
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/catalog-examples/bookmarks-example.yaml

    # npm plugin
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/catalog-examples/npm-example.yaml

    # readme plugin
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/examples/readme-example.yaml

    # todo plugin
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/catalog-examples/todo-example.yaml

    # jira plugin
    - type: url
      target: https://github.com/christoph-jerolimov/best-of-backstage/blob/main/catalog-examples/jira-example.yaml
