name: Tests

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/tests.yaml
      - backstage/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/tests.yaml
      - backstage/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node_version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node_version }}

      - run: yarn install --frozen-lockfile
        working-directory: backstage

      - run: yarn build:all
        working-directory: backstage

      - run: yarn lint:all
        working-directory: backstage

      - run: yarn prettier:check
        working-directory: backstage

      - run: yarn list-deprecations
        working-directory: backstage

      - run: yarn test
        working-directory: backstage

      - run: yarn playwright install chromium
        working-directory: backstage

      - run: yarn test:e2e
        working-directory: backstage
